### ISSUE TITLE
Add a video to a new material of a gameobject at runtime

### ISSUE THREAD

**Issue by ndesseaux** [HISPlayer/Unity_Video_Player#11]
Hi,

I would like to add a new video to a 3D plane at runtime.

I have a HISPlayerManager script who manage all videos inside the scene

I'm using the multiStream Properties.Add function to add a new stream to multiStream but if I play the video with the new video index I get the following error: ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. 

`

        StreamProperties stream = new StreamProperties();
        stream.autoPlay = false;
        stream.material = videoMaterial;
        stream.renderMode = HISPlayerRenderMode.Material;
        stream.url.Add(videoUrl);
        multiStreamProperties.Add(stream);
`

What is the correct method to add a video at runtime ?

**Comment by Nusi-22** [comment]
Hi @ndesseaux ,

We didn't hear from you back.
Since we don't know which OS you are using, here is our answer for all platforms. Hope it helps. 

- In case you aren't using WebGL, this would be the answer:
"The code you are using for adding a stream at runtime is incomplete since the stream is not being added to the player system. Please refer to this example of how to add a new stream at runtime: https://hisplayer.github.io/UnitySamples/#/hisplayer-add-stream-sample?id=hisplayer-add-stream-ui-demo."

- In case you are using WebGL, adding a new Stream at runtime is not possible in the same way, and we would have to provide them with the sample: https://downloads.hisplayer.com/Unity/AllPlatforms/HISPlayer_Runtime_Initialization_Sample.unitypackage.

**Comment by ndesseaux** [comment]
Hi @Nusi-22 , yes we are using WebGL, thank for your response.
